export const CartActions = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  ASSIGN_TO_CART: "ASSIGN_TO_CART",
  CART_OPS_ERROR: "CART_OPS_ERROR",
};
